"""Bind LearningCompletion to roadmap_node_id with unique constraint

Revision ID: 53374d724f3f
Revises: 8f6bc8f669b7
Create Date: 2026-09-02 22:32:17.917662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53374d724f3f'
down_revision: Union[str, Sequence[str], None] = '8f6bc8f669b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('learning_completions') as batch_op:
        batch_op.add_column(sa.Column('roadmap_node_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('skill_name', existing_type=sa.VARCHAR(), nullable=True)
        batch_op.create_index(batch_op.f('ix_learning_completions_roadmap_node_id'), ['roadmap_node_id'], unique=False)
        batch_op.create_unique_constraint('uq_user_roadmap_node_completion', ['user_id', 'roadmap_node_id'])
        batch_op.create_foreign_key('fk_learning_completions_roadmap_node_id', 'roadmap_nodes', ['roadmap_node_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'learning_completions', type_='foreignkey')
    op.drop_constraint('uq_user_roadmap_node_completion', 'learning_completions', type_='unique')
    op.drop_index(op.f('ix_learning_completions_roadmap_node_id'), table_name='learning_completions')
    op.alter_column('learning_completions', 'skill_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('learning_completions', 'completed_at')
    op.drop_column('learning_completions', 'roadmap_node_id')
    # ### end Alembic commands ###
