"""Add roadmap models

Revision ID: 8f6bc8f669b7
Revises: a990a53ad970
Create Date: 2026-09-02 22:14:14.168260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f6bc8f669b7'
down_revision: Union[str, Sequence[str], None] = 'a990a53ad970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_completions_id'), 'learning_completions', ['id'], unique=False)
    op.create_index(op.f('ix_learning_completions_skill_name'), 'learning_completions', ['skill_name'], unique=False)
    op.create_index(op.f('ix_learning_completions_user_id'), 'learning_completions', ['user_id'], unique=False)
    op.create_table('roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_role', sa.String(), nullable=False),
    sa.Column('target_company', sa.String(), nullable=True),
    sa.Column('version_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmaps_id'), 'roadmaps', ['id'], unique=False)
    op.create_index(op.f('ix_roadmaps_user_id'), 'roadmaps', ['user_id'], unique=False)
    op.create_table('roadmap_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('impact', sa.String(), nullable=False),
    sa.Column('estimated_effort_hours', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('prerequisites_json', sa.JSON(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_nodes_id'), 'roadmap_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_roadmap_nodes_roadmap_id'), 'roadmap_nodes', ['roadmap_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_nodes_roadmap_id'), table_name='roadmap_nodes')
    op.drop_index(op.f('ix_roadmap_nodes_id'), table_name='roadmap_nodes')
    op.drop_table('roadmap_nodes')
    op.drop_index(op.f('ix_roadmaps_user_id'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_id'), table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_index(op.f('ix_learning_completions_user_id'), table_name='learning_completions')
    op.drop_index(op.f('ix_learning_completions_skill_name'), table_name='learning_completions')
    op.drop_index(op.f('ix_learning_completions_id'), table_name='learning_completions')
    op.drop_table('learning_completions')
    # ### end Alembic commands ###
