import asyncio
import json
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from sqlalchemy.orm import selectinload
from pydantic import BaseModel
from typing import List, Dict, Any, Optional

from app.core.config import settings
from app.api.deps import get_current_user
from app.core.database import get_db
from app.models.user import User, Resume, ChatSession, ChatMessage
from app.schemas.chat import ChatSessionResponse, ChatSessionHeaderResponse, ChatMessageResponse
from app.agents.orchestrator import agent_executor
from app.services.nlp_service import production_nlp_service
from app.services.memory_service import memory_service

router = APIRouter(prefix="/agent", tags=["agent"])

class QueryRequest(BaseModel):
    message: str
    session_id: Optional[int] = None

class QueryResponse(BaseModel):
    session_id: int
    response: str
    current_agent: str

@router.post("/query", response_model=QueryResponse)
async def query_agent(
    payload: QueryRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    from app.core.config import tool_calls_counter
    tool_calls_counter.set({"count": 0})

    # 1. Retrieve or create ChatSession
    if payload.session_id:
        result = await db.execute(
            select(ChatSession)
            .filter(ChatSession.id == payload.session_id, ChatSession.user_id == current_user.id)
            .options(selectinload(ChatSession.messages))
        )
        session = result.scalars().first()
        if not session:
            raise HTTPException(status_code=404, detail="Chat session not found")
    else:
        title_snippet = payload.message[:30] + "..." if len(payload.message) > 30 else payload.message
        session = ChatSession(user_id=current_user.id, title=title_snippet)
        db.add(session)
        await db.commit()
        await db.refresh(session)

    # 2. Save user message to database
    user_msg = ChatMessage(
        session_id=session.id,
        role="user",
        content=payload.message,
        agent_name="user"
    )
    db.add(user_msg)
    await db.commit()

    # 3. Vector RAG Search: Retrieve user's relevant stored memories
    relevant_memories = await memory_service.search_relevant_memories(db, current_user.id, payload.message, top_k=3)
    memory_context_str = ""
    if relevant_memories:
        mem_lines = [f"- [{m['category']}] {m['memory_text']}" for m in relevant_memories]
        memory_context_str = "\n[User Personal Memory Context]:\n" + "\n".join(mem_lines)

    # 4. Fetch past messages in session for multi-turn history context
    history_result = await db.execute(
        select(ChatMessage)
        .filter(ChatMessage.session_id == session.id)
        .order_by(ChatMessage.created_at.asc())
    )
    past_messages = history_result.scalars().all()
    message_history = []
    
    # Inject memory context if available
    if memory_context_str:
        message_history.append({"role": "user", "content": memory_context_str})

    for msg in past_messages:
        role = "user" if msg.role == "user" else "assistant"
        message_history.append({"role": role, "content": msg.content})

    # 5. Execute Dynamic ReAct Agent or Production NLP Engine
    response_content = ""
    current_agent = "autonomous_react_agent"

    if agent_executor:
        try:
            # Wrap in overall wall-clock execution timeout
            final_state = await asyncio.wait_for(
                agent_executor.ainvoke(
                    {"messages": message_history},
                    config={"recursion_limit": settings.AGENT_MAX_ITERATIONS}
                ),
                timeout=settings.AGENT_EXECUTION_TIMEOUT
            )
            messages = final_state.get("messages", [])
            if messages:
                last_msg = messages[-1]
                response_content = getattr(last_msg, "content", str(last_msg))
                if response_content == "Sorry, need more steps to process this request.":
                    from app.core.config import tool_calls_counter
                    tracker = tool_calls_counter.get()
                    count = tracker.get("count", 0) if tracker else 0
                    if count >= settings.AGENT_MAX_TOOL_CALLS:
                        response_content = json.dumps({
                            "status": "execution_limit_exceeded",
                            "error": "Agent tool call limit exceeded"
                        })
                    else:
                        response_content = json.dumps({
                            "status": "execution_limit_exceeded",
                            "error": "Agent iteration limit exceeded"
                        })
            else:
                response_content = "No response generated by agent."
        except asyncio.TimeoutError:
            response_content = json.dumps({
                "status": "execution_limit_exceeded",
                "error": "Agent execution timeout exceeded"
            })
        except ValueError as e:
            if "Agent tool call limit exceeded" in str(e):
                response_content = json.dumps({
                    "status": "execution_limit_exceeded",
                    "error": "Agent tool call limit exceeded"
                })
            else:
                response_content = json.dumps({
                    "status": "execution_limit_exceeded",
                    "error": f"Agent validation failure: {str(e)}"
                })
        except Exception as e:
            err_name = type(e).__name__
            if "Agent tool call limit exceeded" in str(e):
                response_content = json.dumps({
                    "status": "execution_limit_exceeded",
                    "error": "Agent tool call limit exceeded"
                })
            elif err_name == "GraphRecursionError" or "recursion limit" in str(e).lower() or "recursion" in err_name.lower():
                response_content = json.dumps({
                    "status": "execution_limit_exceeded",
                    "error": "Agent iteration limit exceeded"
                })
            else:
                err_msg = str(e)
                if "rate" in err_msg.lower() or "429" in err_msg or "quota" in err_msg.lower() or "resourceexhausted" in err_msg.lower():
                    response_content = json.dumps({
                        "status": "error",
                        "code": "provider_rate_limited",
                        "error": "AI provider rate limit reached. Please try again in a few moments."
                    })
                else:
                    response_content = json.dumps({
                        "status": "error",
                        "code": "llm_unavailable",
                        "error": f"LLM reasoning service unavailable: {err_msg}"
                    })
    else:
        response_content = json.dumps({
            "status": "error",
            "code": "llm_unavailable",
            "error": "AI agent service is not initialized."
        })

    # 6. Save assistant response to database
    assistant_msg = ChatMessage(
        session_id=session.id,
        role="assistant",
        content=response_content,
        agent_name=current_agent
    )
    db.add(assistant_msg)
    await db.commit()

    return QueryResponse(
        session_id=session.id,
        response=response_content,
        current_agent=current_agent
    )

@router.get("/sessions", response_model=List[ChatSessionHeaderResponse])
async def list_chat_sessions(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    result = await db.execute(
        select(ChatSession)
        .filter(ChatSession.user_id == current_user.id)
        .order_by(ChatSession.updated_at.desc())
    )
    return list(result.scalars().all())

@router.get("/sessions/{session_id}", response_model=ChatSessionResponse)
async def get_chat_session_detail(
    session_id: int,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    result = await db.execute(
        select(ChatSession)
        .filter(ChatSession.id == session_id, ChatSession.user_id == current_user.id)
        .options(selectinload(ChatSession.messages))
    )
    session = result.scalars().first()
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    return session

@router.delete("/sessions/{session_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_chat_session(
    session_id: int,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    result = await db.execute(
        select(ChatSession)
        .filter(ChatSession.id == session_id, ChatSession.user_id == current_user.id)
    )
    session = result.scalars().first()
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    await db.delete(session)
    await db.commit()
